/* eslint-disable @typescript-eslint/no-var-requires */
const sass = require("sass");
const fs = require("fs");
const path = require("path");
const STYLES_DIR = process.cwd() + "/css";
console.log("Generating css file");
const result = sass.compile(path.join(STYLES_DIR, "/sass/custom.scss"), {
  quietDeps: true,
  loadPaths: [process.cwd() + "/node_modules"],
});
const comment = `// DO NOT edit this file. It is autogenrated. run npm run watch to use sass
// No need to review in PRs. ${Math.random()} \n`;

fs.writeFileSync(path.join(STYLES_DIR, "custom.css"), comment + result.css);
console.log("CSS file generated!");
